# Numpy

In [1]:
import numpy as np

### Numpy Array'i Oluşturmak

#### 1 - Liste Üzerinden oluşturmak

In [2]:
a = np.array([1,2,3]) 

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([3.14,4,2])          # sabit tip veri tutar.

array([3.14, 4.  , 2.  ])

In [6]:
np.array([3.14,4,2],dtype="int")

array([3, 4, 2])

#### 2 - Sıfırdan Array Oluşturma

In [7]:
np.zeros(10)          # tek boyutlu array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,2))       # iki boyutlu array

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones([3,4])        

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.full([3,5],4)            # 4'lerden oluşan array oluşturmak için.

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [13]:
np.linspace(0,1,10)              # 0'dan 1'e kdr aralarında eşit fark olan 10 sayı üretme. 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
np.random.normal(10,4,(3,4))     # ortalaması : 10 ,standart sapması : 4 olan iki boyutlu array oluşturma.

array([[13.78775502, 12.60059889, 13.37334674,  5.88415943],
       [ 3.70943845, 10.97180446,  2.70210338,  8.77417834],
       [ 8.05414034, 14.23605755,  9.64824206,  2.73805015]])

In [15]:
np.random.randint(0,10,(3,3))    # 0-10 arası int değerlerden rastgele oluşturulur.(10 sayısı dahil değil)

array([[1, 2, 0],
       [8, 4, 7],
       [5, 4, 2]])

### Özellikleri

* ndim : boyut sayisi
* shape : boyut bilgisi
* size : toplam eleman sayisi
* dtype : array veri tipi

In [16]:
b = np.random.randint(0,10,(2,3))

In [17]:
b

array([[7, 4, 7],
       [4, 8, 2]])

In [18]:
b.ndim

2

In [19]:
b.shape

(2, 3)

In [20]:
b.size

6

In [21]:
b.dtype

dtype('int32')

### Yeniden Şekillendirme (reshaping)

In [22]:
c = np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
d = c.reshape((3,3)) 
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Birleştirme(Concatenation) 

##### tek boyut üzerinde birleştirme

In [24]:
x = np.array([4,6,9])  
y = np.array([3,2,5])

In [25]:
np.concatenate([x,y])

array([4, 6, 9, 3, 2, 5])

In [26]:
z = np.array([1,8,2])

In [27]:
np.concatenate([x,y,z])

array([4, 6, 9, 3, 2, 5, 1, 8, 2])

##### iki boyut üzerinde birleştirme

In [28]:
e = np.array([[1,2,3],
              [4,5,6]]) 

In [29]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.concatenate([e,e])    # axis=0 satır bazında birleştirme yapar.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [31]:
np.concatenate([e,e],axis = 1)   # axis=1 sütun bazında birleştirme yapar.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Array Ayırma (Splitting)

##### tek boyutlu

In [32]:
x = np.array([1,4,3,76,59,3,9,1])

In [33]:
np.split(x,[3,5])

[array([1, 4, 3]), array([76, 59]), array([3, 9, 1])]

In [34]:
a,b,c = np.split(x,[3,5]) 

In [35]:
a

array([1, 4, 3])

In [36]:
b

array([76, 59])

In [37]:
c

array([3, 9, 1])

##### iki boyutlu

In [38]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.vsplit(m , [2])               # ikiye kdr olan kısmı yatay olarak böl.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [40]:
ust , alt = np.vsplit(m , [2])

In [41]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
np.hsplit(m,[2])                 # dikey olrk böler.

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [44]:
sag , sol = np.hsplit(m,[2])

In [45]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [46]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### Array Sıralama (Sorting)

##### tek boyutlu

In [47]:
v = np.array([2,1,4,3,5])

In [48]:
np.sort(v)               # küçükten büyüğe sıralar.Veri setinin orijinal yapısını bozmaz.

array([1, 2, 3, 4, 5])

In [49]:
v

array([2, 1, 4, 3, 5])

In [50]:
v.sort()                 # kalıcı olrk sıralama yapar.
v

array([1, 2, 3, 4, 5])

##### iki boyutlu 

In [51]:
m = np.random.normal(20,5,(3,3))      # ortalaması :20  ,standart sapması :5 olan array oluşturma.
m

array([[21.77681736, 17.89209625, 24.98857039],
       [19.15088547, 29.04075687, 20.22610146],
       [16.21452248, 12.32651734, 17.79716436]])

In [52]:
np.sort(m,axis = 1)                   # satırları küçükten büyüğe sıralar.

array([[17.89209625, 21.77681736, 24.98857039],
       [19.15088547, 20.22610146, 29.04075687],
       [12.32651734, 16.21452248, 17.79716436]])

In [53]:
np.sort(m,axis = 0)                   # sütunları küçükten büyüğe sıralar.

array([[16.21452248, 12.32651734, 17.79716436],
       [19.15088547, 17.89209625, 20.22610146],
       [21.77681736, 29.04075687, 24.98857039]])

### Index ile Elemanlara Erişmek 

In [54]:
a = np.random.randint(10, size = 5)
a

array([6, 3, 5, 9, 3])

In [55]:
a[-1]

3

In [56]:
a[0] = 56          # eleman degiştirme
a

array([56,  3,  5,  9,  3])

In [57]:
m = np.random.randint(10, size = (3,4))  # iki boyutlu array oluşturma.
m

array([[3, 0, 9, 8],
       [0, 3, 2, 5],
       [1, 1, 7, 7]])

In [58]:
m[1,3]

5

In [59]:
m[1,3]= 99             # eleman degiştirme
m

array([[ 3,  0,  9,  8],
       [ 0,  3,  2, 99],
       [ 1,  1,  7,  7]])

In [60]:
m.dtype

dtype('int32')

In [61]:
m[1,3] = 2.2           # 2.2'nin ondalık kısmı olmadan ekler.
m 

array([[3, 0, 9, 8],
       [0, 3, 2, 2],
       [1, 1, 7, 7]])

### Slicing ile Elemanlara Erişmek 

In [62]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [63]:
a[1::2]

array([21, 23, 25, 27, 29])

In [64]:
a[3::3]

array([23, 26, 29])

##### iki boyutlu slice işlemleri

In [65]:
k = np.random.randint(10, size = (5,5))
k

array([[1, 2, 4, 5, 9],
       [6, 5, 8, 3, 7],
       [3, 9, 6, 3, 1],
       [2, 5, 3, 0, 1],
       [0, 2, 7, 7, 3]])

In [66]:
k[:,0]     # bütün satırları seç,1.sütuna eriş

array([1, 6, 3, 2, 0])

In [67]:
k[0,:]     # 1.satır , tum sütunları seç

array([1, 2, 4, 5, 9])

In [68]:
k[0:2,0:3]

array([[1, 2, 4],
       [6, 5, 8]])

In [69]:
k[1:,2]    

array([8, 6, 3, 7])

In [70]:
k[:,:2]

array([[1, 2],
       [6, 5],
       [3, 9],
       [2, 5],
       [0, 2]])

### Fancy Index ile Elemanlara Erişmek

##### tek boyut

In [71]:
v = np.arange(0,20,3)
v

array([ 0,  3,  6,  9, 12, 15, 18])

In [72]:
v_deger=[1,3,5]

In [73]:
v[v_deger]

array([ 3,  9, 15])

##### iki boyut

In [74]:
m = np.random.randint(0,10,(3,3))
m

array([[0, 0, 2],
       [7, 9, 3],
       [8, 4, 6]])

In [75]:
satir = np.array([0,1])  
sutun = np.array([1,2])

In [76]:
m[satir,sutun]

array([0, 3])

### Koşullu Eleman İşlemleri

In [77]:
v = np.arange(0,31,3)

In [78]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [79]:
v<4

array([ True,  True, False, False, False, False, False, False, False,
       False, False])

In [80]:
v[v<20]

array([ 0,  3,  6,  9, 12, 15, 18])

### Matematiksel İşlemler

In [81]:
v = np.array([3,6,8,2,9])

In [82]:
np.subtract(v,1)        # v - 1

array([2, 5, 7, 1, 8])

In [83]:
np.add(v,1)             # v + 1

array([ 4,  7,  9,  3, 10])

In [84]:
np.multiply(v,2)        # v*2

array([ 6, 12, 16,  4, 18])

In [85]:
np.divide(v,3)          # v / 3

array([1.        , 2.        , 2.66666667, 0.66666667, 3.        ])

In [86]:
np.power(v,3)           # v**3

array([ 27, 216, 512,   8, 729], dtype=int32)

In [87]:
np.mod(v,2)              # v % 2  ikiye bölümünden kalanlar

array([1, 0, 0, 0, 1], dtype=int32)

In [88]:
np.absolute(np.array([-3]))     # mutlak değer

array([3])

In [89]:
np.sin(360)          # trigonometrik işlemler

0.9589157234143065

In [90]:
np.log(v)            # logaritmasını alır

array([1.09861229, 1.79175947, 2.07944154, 0.69314718, 2.19722458])

In [91]:
np.log2(v) 

array([1.5849625, 2.5849625, 3.       , 1.       , 3.169925 ])

### Alt Küme Üzerinde İşlem Yapmak

In [92]:
h = np.random.randint(10, size = (5,5))
h

array([[2, 1, 0, 7, 8],
       [1, 9, 6, 5, 7],
       [5, 3, 1, 3, 4],
       [8, 9, 2, 7, 9],
       [3, 0, 8, 0, 7]])

In [93]:
alt_a = h[0:3,0:2].copy()       # .copy()  metodu ile alt kümede yaptığımız değişikler ana arrayi etkilemez. 
alt_a

array([[2, 1],
       [1, 9],
       [5, 3]])

In [94]:
alt_a[2,1] = 66
alt_a

array([[ 2,  1],
       [ 1,  9],
       [ 5, 66]])

In [95]:
h

array([[2, 1, 0, 7, 8],
       [1, 9, 6, 5, 7],
       [5, 3, 1, 3, 4],
       [8, 9, 2, 7, 9],
       [3, 0, 8, 0, 7]])